#include<iostream>
#include<random>
#include<time.h>

using namespace std;


void greet()
{
	
	cout<<"Hello user! "<<endl;
	cout<<"Welcome to the guessing game "<<endl;
	cout<<"You have to guess a positive number below 100 generated by "<<endl<<"the computer in minimum tries"<<endl<<endl;
	
}



int main()
{

	int guess,num,tries=0;
	char ch='y';
		
		greet();


		srand(time(0));
		num=rand()%100;

	while(guess!=num||ch=='y'||ch=='Y')
	{

		cout<<"Take a guess"<<endl;
		cin>>guess;
		tries++;


				if (guess>num&&guess<100)
					cout<<"Too high.. Go low "<<endl;
				else if(guess<num&&guess>=0)
					cout<<"Too low.. Go high "<<endl;
				else if(guess>=100||guess<0)
				{
					cout<<"Incorrect Number Entered"<<endl;
					cout<<"Try again : "<<endl<<endl;
				}
				else
				{

					cout<<"Correct guess! Number of tries = "<<tries<<endl;
					cout<<endl<<endl<<"Do you want to play again : Y/N "<<endl;
					cin>>ch;

						if(ch=='n'||ch=='N')
						{
							cout<<"Thanks for playing.. "<<endl;
							break;
						}
						else if(ch=='Y'||ch=='y')
						{
							tries=0;
							num=rand()%100;
						}
						else if(ch!='y'||ch!='Y'||ch=='n'||ch=='N')
							cout<<"Incorrect Choice Entered"<<endl;	

				}

	}


	return 0;
}